### ISSUE TITLE
linter.ymlでSuper Linterのslim v4指定を公式ドキュメントの最新記法に修正

### ISSUE THREAD

**Issue by ttsukagoshi** [ttsukagoshi/gas-github#123]
```yml
jobs:
  build:
    steps:
    ...
      - name: Lint Code Base
        uses: docker://ghcr.io/github/super-linter:slim-v4
```
を
```yml
jobs:
  build:
    steps:
    ...
      - name: Lint Code Base
        uses: github/super-linter:slim-v4
```
に書き換える

---

参考： https://github.com/github/super-linter#images
